config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# get '/', to: 'pages#home'
get '/about', to: 'pages#about'

root 'pages#home'

get 'signup', 		to: 'users#new'
get 'login',  		to: 'sessions#new'
post 'login', 		to: 'sessions#create'
delete 'logout',	to: 'sessions#destroy'
#post 'users', to: 'users#create'

resources :users, except: [:new]
resources :articles

resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 3000 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }

	validates :username,
			   presence:true, uniqueness:{ case_sensitive: false },
			   length:{ minimum:3, maximum:25 }

	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	validates :email,
			   presence:true, uniqueness:{ case_sensitive: false },
			   format: { with: VALID_EMAIL_REGEX },
			   length: { maximum:105 }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user, :logged_in?

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end


def logged_in?
	!!current_user
end

def require_user
	if !logged_in?
		flash[:danger] = "You must be logged in to perform that action."
		redirect_to root_path
	end
end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:info] = "Article Was Successfully Created!"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @article.update(article_params)
		flash[:info] = "Article Was Updated Successfully!"
		redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article Was Deleted Successfully!"
		redirect_to articles_path
	end


	private
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own article"
			redirect_to root_path
		end
	end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:edit, :update, :show, :destroy]
	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:info] = "Category created successfully."
			redirect_to categories_path(@categories)
		else
			render :action => 'new'
		end
	end

	def show
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def edit
	end

	def update
		if @category.update(category_params)
		flash[:info] = "Category Was Updated Successfully!"
		redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	private
	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || ( logged_in? and !current_user.admin? )
			flash[:danger] = "Only admin users can perform that action."
			redirect_to root_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		# debugger
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in."
			redirect_to users_path(user)
		else
			flash.now[:danger] = "Error : There was something wrong with your login information."
			render 'new'

	end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out Successfully."
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show, :destroy]
	before_action :require_user, only: [:edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update]
	before_action :require_admin, only: [:destroy]

	def index
	@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
	@user = User.new
	render 'users/new'
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:info] = "Welcome to Weblog #{@user.username}"
			redirect_to user_path(@user)
		else
			render :action => 'new'
			#redirect_to new_user_path(@user)
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
		flash[:info] = "User Was Updated Successfully!"
		redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user.destroy
		flash[:danger] = "User and all articles created by user have been deleted."
		redirect_to users_path
	end

	private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own account."
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? && !current_user.admin?
			flash[:danger] = "Only admin users can perform that action."
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80 } )
	size = options[:size]
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	image_tag(gravatar_url, alt: user.username, class: "circle rounded")
	end

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

<div class="card article">
  <div class="card-header article">
    <%= link_to article.title, article_path(article) %>
       <span class="article-user"> <small><strong>Publisher : </strong> <%= article.user.username if article.user %> , <%= time_ago_in_words(article.created_at) %> ago , Last updated : <%= time_ago_in_words(article.updated_at) %> ago</small></span>
  </div>
  <div class="card-body display">
    <p class="card-text"><%= truncate(article.description, length: 400) %></p>
  <% if article.categories.any? %>
  <p> <small class="custom-small">Categories : </small> <%= render article.categories  %></p>
  <% end %>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
    <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-primary" %>
	<%= link_to "Delete Article", article_path(article), method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-danger" %>
  <% end %>
	<%= link_to "Show Article", article_path(article), class: "btn btn-info" %>

  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="container">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <%= f.label :title, class: "label" %>
        <%= f.text_field :title, class: "form-control", placeholder: "Article Title", autofocus: true %>
    </div>
    <div class="form-group">
        <%= f.label :description, class: "description" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Article Description", autofocus: true, rows: 7 %>
    </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox custom") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>


    <div class="form-group">
        <%= f.submit  class: "btn btn-primary btn-lg" %>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
        [<%= link_to "Cancel Request and Go Back", articles_path %>]
    </div>
</div>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2>Listing All Articles</h2>
<div class="new-article">

<%= link_to "Create a New Article", new_article_path, class: "btn btn-warning" %>

</div>

<div class="pagination-of articles">
	<%= will_paginate @articles %>
</div>
<div class="clearfix"></div>
<%= render 'article', obj: @articles %>

<div class="clearfix"></div>

<div class="pagination-of articles">
	<%= will_paginate @articles %>
</div>

<div class="clearfix"></div>

app/views/articles/new.html.erb
<h2>Create an Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="card bg-ligth col-xs-8 article_head">

<h2 align="alert-heading center article-title"> <strong class="article_t">Title :</strong>
    <span class="article-t"><%= @article.title %></span>
</h2>
</div>

<div class="clearfix">
</div>

<div class="card bg-light col-xs-8 col-xs-offset-2">
	<div class="row">
	<div class="col-sm-12 center" align="center">
		<%= link_to gravatar_for(@article.user), user_path(@article.user) if @article.user %>
	</div>
</div>
<div class="clearfix">

</div>
<h4 align="center"> <%= @article.user.username %>'s articles</h4>

	<h4 class="center description"> <strong class="article_t"> Description  </strong> </h4>
	<hr>
	<span class="article_d">
    <%= simple_format(@article.description) %>
	</span>
	<% if @article.categories.any? %>
	<p> <small class="custom-small">Categories : </small> <%= render @article.categories  %></p>
	<% end %>
	<span class="article-user"> <strong>Published by : </strong>  <%= @article.user.username %>

	</span>
<div class="articles-action">
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete This Article", article_path(@article), method: :delete, 				data: { confirm: "Are You Sure you want to delete the article?" }, 				class: "btn btn-xs btn-danger" %>
<% end %>
    <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>

app/views/categories/_category.html.erb
<span class="badge">
	<%= link_to category.name, category_path(category), class:"badge  badge-pill badge-primary custom" %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class="container">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>

    <div class="form-group">
        <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
    <% end %>
    <div class="clearfix">
    </div>
    <div class="col-xs-4 col-xs-offset-4">
    <%= link_to "All Categories", categories_path, class: "btn btn-danger btn-lg" %>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2>Listing All Categories</h2>
<% if logged_in? && current_user ==  current_user.admin? %>
<%= link_to "Create New Category", new_category_path, class: "btn btn-primary" %>
<% end %>
<div class="pagination-of articles">
  <%= will_paginate @articles %>
</div>
<% @categories.each do |category| %>
<div class="clearfix"></div>
<div class="card article">
  <div class="card-header article">
    <%= link_to category.name, category_path(category) %>
    <div class="article-count"><small class="badge badge-primary""><%= pluralize(category.articles.count, "Article")%></small></div>
       <span class="article-user"> <small>Created : <%= time_ago_in_words(category.created_at) %> ago , Last updated : <%= time_ago_in_words(category.updated_at) %> ago</small></span>
  </div>
    <% if logged_in? && (current_user ==  current_user.admin?) %>
  <div class="card-body display">
    <%= link_to "Edit Category", edit_category_path(category), class: "btn btn-primary" %>
  </div>
  <% end %>
</div>
<% end %>
<div class="clearfix"></div>

<div class="pagination-of articles">
  <%= will_paginate @articles %>
</div>
<div class="clearfix"></div>

app/views/categories/new.html.erb
<h1 align="center">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= "Category: " + @category.name %></h2>
<div class="new-article">

<%= link_to "Create a New Article", new_article_path, class: "btn btn-warning" %>

</div>

<div class="pagination-of articles">
	<h4><%= link_to "Edit Category", edit_category_path(@category), class:"badge badge-primary" %></h4>
	<%= will_paginate @category_articles %>
</div>
<div class="clearfix"></div>
<%= render 'articles/article', obj: @category_articles %>

<div class="clearfix"></div>

<div class="pagination-of articles">
	<%= will_paginate @category_articles %>
</div>

<div class="clearfix"></div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="http://guides.rubyonrails.org">My personal blog</a>
		</small>
		<nav>
			<ul>
				<li>
					<%= link_to "About", about_path %>
				</li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class='alert alert-<%= "#{name}" %>' role="alert">
	<a href="#" class="close" data-dismiss="alert">&#215</a>
    <%= msg %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "WeBlog", root_path, class:"navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Articles", articles_path, class: "btn nav-link active" %>
            </li>
            <%= link_to "Users", users_path, class: "btn nav-link" %>
            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
                    <a class="dropdown-item" href="#">Another action</a>
                    <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <% end %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "All categories", categories_path, class: "dropdown-item" %>
                    <% Category.all.each do |category| %>
                    <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
                    <% end %>
                    <div class="dropdown-divider"></div>
                    <% if logged_in? and current_user.admin? %>
                    <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
                    <% end %>
                </div>
    </li>
    </ul>
    </div>
    <ul class="navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %> <small class="badge badge-pill badge-danger">
                    <%= "Admin" if current_user.admin? %>
                    <%= "User" if !current_user.admin? %>
                    </small>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "View Profile",user_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
        <% end %>
    </ul>
    </div>
</nav>
<div class="clearfix">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Karla&display=swap" media="screen" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,400i&display=swap" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About Page</h1>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-4 page-title">WeBlog</h1>
  <%= link_to "Sign Up Now", signup_path , class: "btn btn-danger btn-lg" %>
  <div class="clearfix"></div>
  <div>
  <%= link_to "Login", login_path , class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<% obj.errors.full_messages.each do |msg| %>
<div class="alert alert-danger" role="alert">
    <%= msg %>
</div>
<% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="container">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <%= f.label :username, class: "label" %>
        <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
    </div>

    <div class="form-group">
        <%= f.label :email, class: "email" %>
        <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
    </div>

    <div class="form-group">
        <%= f.label :password, class: "password" %>
        <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: true %>
    </div>
    <div class="form-group">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account",  class: "btn btn-primary btn-lg") %>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
        [
        <%= link_to "Cancel Request and Go Back", articles_path %>]
    </div>
</div>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center" class="users"> All Blog Users </h1>

<div class="pagination-of articles">
	<%= will_paginate @articles %>
</div>
<div class="clearfix"></div>
<% @users.each do |user| %>

<div class="card text-center w-50 bg-white border-primary" align="center">
  <div class="card-header">
    <span class="image-user rounded img-circle img-rounded"><%= link_to gravatar_for(user), user_path(user), size: 150 %></span>
<div class="clearfix"></div>
   <h5 class="card-title"> <%= link_to user.username, user_path(user), class: "test" %></h5>
    <p class="card-text"><small>Total published : <%= pluralize(user.articles.count, "articles") if user.articles %></small></p>
    <% if logged_in? and current_user.admin? %>
    <p class="card-text">
    <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all articles?"}, class: "btn btn-danger" %>
    <% end %>
</p>

	<span class="article-user"><small>
		Last update : <%= time_ago_in_words(user.updated_at) %> ago</small>
	</span>
</div>
</div>
<div class="clearfix"></div>

<% end %>

<div class="pagination-of articles">
	<%= will_paginate @articles %>
</div>

<div class="clearfix"></div>

app/views/users/new.html.erb
<h2>Create User</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s page</h1>

<div class="row">
	<div class="col-sm-12 center" align="center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<div class="clearfix">

</div>
<h4 align="center"> <%= @user.username %>'s articles</h4>

<div class="clearfix"></div>

<div class="pagination-of articles">
	<%= will_paginate @user_articles %>
</div>

<div class="clearfix"></div>
<%= render 'articles/article' , obj: @user.articles %>
<div class="clearfix"></div>

<div class="pagination-of articles">
	<%= will_paginate @user_articles %>
</div>
<div class="clearfix"></div>